### ISSUE TITLE
Tiempo de espera a un autobús en parada

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-autobus#11]
Para representar el tiempo de espera --en tiempo real-- de un autobús en una parada, después de haber valorado que se relacionara con `tmjourney:TimetabledPassingTime`, hemos convenido crear la clase `esautob:RealTimePassing` que es una subclase de `sosa:Observation` que tiene como OP `sosa:featureOfInterest` con `tmjourney:PointInLinkSequence`.

Esta clase tendrá como DP:
- `sosa:resultTime xsd:dateTime`
- `esautob:expectedArrival xsd:duration`

**Comment by ednaru** [comment]
Está modificado en el diagrama. Depende de la solución al issue #9. Una opción es colocarlo como una clase entre PoinInLinkSequence y Parada.

**Comment by ednaru** [comment]
Se ha colocado en el diagrama ruta-viaje de acuerdo a la propuesta. Modificar en la ontología.

**Comment by flowsta** [comment]
Añadido a la ontología y modificado en el ejemplo
