### ISSUE TITLE
`TimetabledPassingTime` y `TimingPointInJourneyPattern`

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-autobus#12]
Después de haber valorado que `TimetabledPassingTime` y `TimingPointInJourneyPattern` se representaran en el vocabulario de autobús y que el tiempo de espera en parada --tiempo real-- se relacionara con estas clases, hemos convenido que no se relacionen. Lo representamos en Transmodel.

**Comment by ednaru** [comment]
Se decide de acuerdo al issue #18
