### ISSUE TITLE
Diagramas en SVG

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-autobus#15]
Dado que estamos utilizando draw.io para la creación de diagramas y permite la exportación a SVG se podría valorar si se emplea SVG para los diagramas o no.
Consideraciones:
- Peso: o tamaño de la imagen. Un PNG de 132 Kb pesa 44 Kb en SVG
- Soporte de los navegadores: si no se requiere interactividad se puede usar el elemento img de HTML como con cualquier otra imagen.

**Comment by ocorcho** [comment]
No hay normas predefinidas en este sentido. Ambas opciones son adecuadas.

**Comment by flowsta** [comment]
Ok, pongo SVG de momento
