### ISSUE TITLE
Parada

### ISSUE THREAD

**Issue by flowsta** [CiudadesAbiertas/vocab-transporte-autobus#16]
# Enfoque `Place Point`
Así lo hemos representado ahora.
- En Transmodel `Place` es una descripción genérica de `Zone`: `Place genericDescriptionOf Zone`.
- La definición de Place es "A geographic place of any type which may be specified as the origin or destination of a trip. A PLACE may be represented as a POINT (dimension 0) , a road section (dimension 1) or a ZONE (dimension 2).
- Asumimos que `Place` puede ser una descripción genérica de `Point`: `Place genericDescriptionOf Point`.

# Enfoque `Place Zone`
Si no hacemos esa asunción, en Transmodel `Zone` está representado por `Point`, luego:
- `Place genericDescriptionOf Zone`
- `Zone representedBy Point`

# Enfoque `Stop Place`
`Stop Place` comprende todo lo relativo a paradas. 
- `ScheduleStopPoint` se relaciona con `StopAssignment` a través de `to`
- `StopAssignment` con `StopPlace` a través de `for`

**Comment by ednaru** [comment]
- Enfoque Place Point no lo propongo porque al parecer la suposición de Place aGenericDescriptionOf Point es de una versióin anterior de Transmodel.
- Enfoque StopPlace no lo propongo porque valdría solo para JourneyPattern y no para Route.
- Propongo una variante de Place Zone, pero solo poniendo la propiedad inversa de representedBy que es functionalCentroidFor, y poniendo Place como subclase de Zona. Está ya reflejada en el diagrama.

**Comment by ednaru** [comment]
Colocar clases y propuesta de Place Zone. Al parecer Place y Zone forman parte de tmcommons

**Comment by flowsta** [comment]
Hecho!
