### ISSUE TITLE
Eliminar clases y propiedades de ruta-viaje

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-autobus#18]
En concordancia con el ejemplo madrid-linea-130-mayo-2020 se ha modificado el diseño de ruta-viaje. https://drive.google.com/file/d/1pawZQji86-9VmlgenMLeFwtfS0-FffEz/view?usp=sharing
Se debe eliminar de la ontología las siguientes clases: TimetabledPassingTime, PropertyOfDay, OperatingPeriod, OperatingDay y todas sus propiedades.
Eliminar las propiedades que no se estén utilizando de las clases DayTypeAssignment

**Comment by flowsta** [comment]
Eliminadas de ejemplos y ontología
