### ISSUE TITLE
Cambiar vcard:address a schema:address

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-transporte-autobus#7]
Cambiar la propiedad vcard:address a schema:address que va de Parada a DireccionPostal

**Comment by flowsta** [comment]
La relación (OB, object property) entre lo que finalmente sea Parada y su dirección postal será `schema:address` con la clase `esdir:DireccionPostal` tal como aparece en el vocabulario de [Agenda municipal](http://vocab.ciudadesabiertas.es/def/sector-publico/agenda-municipal/index-es.html)

**Comment by ednaru** [comment]
Se cambió en el diagrama.

**Comment by flowsta** [comment]
Hecho en la ontología y los ejemplos
